# Generated by Django 5.0 on 2024-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('stuID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('stuName', models.CharField(max_length=30)),
                ('numPH1', models.IntegerField()),
                ('numNH1', models.IntegerField()),
                ('numPH2', models.IntegerField()),
                ('numNH2', models.IntegerField()),
                ('numBackup', models.IntegerField()),
                ('timeOff', models.ManyToManyField(to='shifts.calendar')),
            ],
        ),
    ]
