# Generated by Django 5.0 on 2024-01-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_calendar_stuid_calendar_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='dayNum',
            field=models.IntegerField(null=True),
        ),
    ]
